---
description: Tensorflow i√ßin hata notlarƒ±
---

# üêû Hata Notlarƒ±

## 'conda' is not recognized as an internal or external command

`Anaconda Prompt` √ºzerinden terminal i≈ülemlerinize devam etmeniz durumunda sorun gidecektir.

## '...' is not recognized as an internal or external command

[Gerekli Paketlerin Kurulumlarƒ±]() tamamlanmadƒ±ƒüƒ± i√ßin bu hata ile kar≈üƒ±la≈üƒ±yor olabilirsiniz.

## 'ImportError: No module named' Hatalarƒ±

PythonPath ayarlanmadƒ±ƒüƒ± i√ßin bu hata ile kar≈üƒ±la≈ümaktasƒ±nƒ±z.

```bash
set PYTHONPATH=%TENSORFLOW%\models\research;%TENSORFLOW%\models\research\slim;%TENSORFLOW%\models\research\object_detection
```

> D√∂k√ºmandaki ilgili alana y√∂nelmek i√ßin [buraya]() tƒ±klayabilrisin.

## 'dict\_keys' object does not support indexing

A√ßƒ±klama linki i√ßin [buraya](https://github.com/tensorflow/models/pull/6044/files) bakabilirsin.

```bash
start %TENSORFLOW%\models\research\object_detection\models\feature_map_generators.py
```

* Satƒ±r 518'deki yere alttaki kodu yapƒ±≈ütƒ±rƒ±n

```python
image_features = image_features[list(image_features.keys())[0]]
```

## Object was never used \(type \)

> Yakƒ±nda..

## 'unicodeescape' codec can't decode bytes in position

Modelinizin `.config` dosyanƒ±za yazdƒ±ƒüƒ±n tam yol verilerinde `\` yerine `/` veya `\\` kullanmalƒ±sƒ±nƒ±z.

## Allocation of X exceeds 10% of system memory

* Rastgeldiƒüim bu [kaynaƒüa](https://github.com/tensorflow/tensorflow/issues/18736#issuecomment-385976699) g√∂re **ssd\_mobilenet\_v2\_coco modeline** √∂zg√º bir hatadƒ±r.
* Hatanƒ±n √ß√∂z√ºm kaynaƒüƒ± i√ßin [buraya](https://github.com/tensorflow/tensorflow/issues/18736#issuecomment-388709455) tƒ±klayabilirsin

## google.protobuf.text\_format.ParseError, Expected string but found

Config dosyalarƒ±nƒ±n text edit√∂r √ºzerinden d√ºzenlemesi durumunda, t√ºrk√ße karakterler i√ßin text edit√∂r√º yapƒ±yƒ± deƒüi≈ütirmekte ve tensorflow bunu algƒ±layamamaktadƒ±r. Sorunu √ß√∂zmek i√ßin alttakiler yardƒ±mƒ±yla `.config` dosyasƒ±nƒ± d√ºzenleyin:

* VsCode
* Notepad++
* Sublime
* Atom

> Harici kaynak i√ßin [buraya](https://github.com/tensorflow/models/issues/1897#issuecomment-313879598) bakabilirsin.

## Value Error: No Variable to Save

Model eƒüitimi yapƒ±ldƒ±ƒüƒ± sƒ±rada gelen bir hatadƒ±r, √ß√∂z√ºm√º i√ßin `.config`dosyanƒ±zƒ± bu ≈üekilde d√ºzenleyin:

```text
train_config: {
  ...
  fine_tune_checkpoint: "./pre_trained_model/model.ckpt"
  fine_tune_checkpoint_type:  "detection"
  ...
}
```

> `ssd_mobilenet_v1_quantized_300x300_coco14_sync` modelinde test edilmi≈ütir.

